[package]
name = "markov_ngram"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version="0.8.4", features=["small_rng"] }
regex = "1.5.4"
